name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1.4.2
    
    - name: NPM install
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Commit changes and add CNAME
      run: |
        cd dist
        git config --global user.email "ticked.deployment@jusola.xyz"
        git config --global user.name "Ticked deployment"
        git init
        echo ticked.jusola.xyz > CNAME
        git add -A
        git commit -m "deploy"
    
    - name: Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'dist'
        force: true
        directory: './dist'
